<a href="https://colab.research.google.com/github/ramanji567/pandas_analysis-/blob/main/pandas_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Task 1:Load and Inspect the Data

In [173]:
import pandas as pd
import numpy as np
data = {
    "transaction_id":range(1,21),
    "data":pd.date_range('2024-10-01', periods =20,freq ='D'),
    "region":['North','South','East','West',None,'North','South',None,'East','West',
              'North','South','East','West','North',None,'East','West','North','South'],
    "Product_category":['Electronics','Clothing',None,'Books','Electronics','Home','Clothing',
                        'Books','Electronics',None,'Home','Clothing','Books','Electronics',
                        'Home','Clothing','Books','Electronics','Home','Clothing'],
    "sales_amount":[1200,450,890,None,1500,670,None,340,2100,780,560,None,420,1800,
                    920,510,380,None,1100,640],
    "quantity":[2,5,3,1,None,4,2,3,1,5,3,2,None,1,4,3,2,1,None,4],
    "customer_age":[25,34,None,45,29,None,38,52,27,41,
                    33,None,48,26,35,42,None,31,39,44],
    "payment_method":['Credit Card','UPI','Cash','Debit Card','Credit Card',
                      'UPI','Cash',None,'Credit Card','UPI','Debit Card',
                      'Cash','Credit Card',None,'UPI','Cash','Debit Card',
                      'Credit Card','UPI',None]
}
df = pd.DataFrame(data)
df

,transaction_id,data,region,Product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,None,890.0,3.0,NaN,Cash
3,4,2024-10-04,West,Books,NaN,1.0,45.0,Debit Card
4,5,2024-10-05,None,Electronics,1500.0,NaN,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,NaN,UPI
6,7,2024-10-07,South,Clothing,NaN,2.0,38.0,Cash
7,8,2024-10-08,None,Books,340.0,3.0,52.0,None
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,None,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,NaN,2.0,NaN,Cash
12,13,2024-10-13,East,Books,420.0,NaN,48.0,Credit Card
13,14,2024-10-14,West,Electronics,1800.0,1.0,26.0,None
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,None,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,NaN,Debit Card
17,18,2024-10-18,West,Electronics,NaN,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,NaN,39.0,UPI
19,20,2024-10-20,South,Clothing,640.0,4.0,44.0,None

1.Display basic information using df.info()

In [174]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   transaction_id    20 non-null     int64
 1   data              20 non-null     datetime64[ns]
 2   region            17 non-null     object
 3   Product_category  18 non-null     object
 4   sales_amount      16 non-null     float64
 5   quantity          17 non-null     float64
 6   customer_age      16 non-null     float64
 7   payment_method    17 non-null     object
dtypes: datetime64[ns](1), float64(3), int64(1), object(3)
memory usage: 1.4+ KB

2.count the missing values in each column using df.isna().sum()

In [175]:
df.isna().sum()

transaction_id      0
data                0
region              3
Product_category    2
sales_amount        4
quantity            3
customer_age        4
payment_method      3
dtype: int64

Task 2:Handle Missing Values

1:Region & Product_category:Fill with mode(most frequent value)

In [176]:
mode_region = df['region'].mode()[0]
df['region']= df['region'].fillna(mode_region)

In [177]:
mode_product=df['Product_category'].mode()[0][1]
df['Product_category']=df['Product_category'].fillna(mode_product)

2:Sales_amount: Fill with median

In [178]:
median_sales = df['sales_amount'].median()
df['sales_amount'] = df['sales_amount'].fillna(median_sales)

3:Quantity :Fill using forward fill (ffill)

In [179]:
df['quantity']=df['quantity'].fillna(method='ffill')

/tmp/ipykernel_157/1821486030.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['quantity']=df['quantity'].fillna(method='ffill')

4.Customer_age:Fill with mean(rounded to integer)

In [180]:
mean_customer = df['customer_age'].mean()
df['customer_age']=df['customer_age'].fillna(round(mean_customer))
mean_customer

np.float64(36.8125)

5.Payment_method: Drop rows where payment_method is missing

In [181]:
df = df.dropna()
df

,transaction_id,data,region,Product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,l,890.0,3.0,37.0,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,37.0,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,l,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,37.0,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,37.0,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI

Verify no missing values remain using df.isna().sum()

In [182]:
df.isna().sum()

transaction_id      0
data                0
region              0
Product_category    0
sales_amount        0
quantity            0
customer_age        0
payment_method      0
dtype: int64

Task: 3 GroupBy Analysis

1: calculate total sales by region

In [183]:
total_sales = df.groupby('region')['sales_amount'].sum()
total_sales

region
East     3790.0
North    6460.0
South    1900.0
West     2230.0
Name: sales_amount, dtype: float64

2 : calculate average sales by product_category

In [184]:
df

,transaction_id,data,region,Product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,l,890.0,3.0,37.0,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,37.0,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,l,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,37.0,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,37.0,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI

In [185]:
average_sales = df.groupby('Product_category')['sales_amount'].mean()
average_sales

Product_category
Books           508.333333
Clothing        602.500000
Electronics    1381.250000
Home            812.500000
l               835.000000
Name: sales_amount, dtype: float64

In [186]:
df

,transaction_id,data,region,Product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,l,890.0,3.0,37.0,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,37.0,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,l,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,37.0,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,37.0,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI

3 . Group by both region and Product_category and total sales

In [187]:
df.groupby(['region','Product_category'])['sales_amount'].sum()

region  Product_category
East    Books                800.0
        Electronics         2100.0
        l                    890.0
North   Clothing             510.0
        Electronics         2700.0
        Home                3250.0
South   Clothing            1900.0
West    Books                725.0
        Electronics          725.0
        l                    780.0
Name: sales_amount, dtype: float64

In [188]:
df

,transaction_id,data,region,Product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,l,890.0,3.0,37.0,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,37.0,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,l,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,37.0,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,37.0,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI

group by total quantity

In [189]:
df.groupby(['region','Product_category'])['quantity'].sum()

region  Product_category
East    Books                4.0
        Electronics          1.0
        l                    3.0
North   Clothing             3.0
        Electronics          3.0
        Home                12.0
South   Clothing             9.0
West    Books                1.0
        Electronics          1.0
        l                    5.0
Name: quantity, dtype: float64

In [190]:
df

,transaction_id,data,region,Product_category,sales_amount,quantity,customer_age,payment_method
0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,3,2024-10-03,East,l,890.0,3.0,37.0,Cash
3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,6,2024-10-06,North,Home,670.0,4.0,37.0,UPI
6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
9,10,2024-10-10,West,l,780.0,5.0,41.0,UPI
10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
11,12,2024-10-12,South,Clothing,725.0,2.0,37.0,Cash
12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
16,17,2024-10-17,East,Books,380.0,2.0,37.0,Debit Card
17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI

use reset index to flatten

In [191]:
df.reset_index()

,index,transaction_id,data,region,Product_category,sales_amount,quantity,customer_age,payment_method
0,0,1,2024-10-01,North,Electronics,1200.0,2.0,25.0,Credit Card
1,1,2,2024-10-02,South,Clothing,450.0,5.0,34.0,UPI
2,2,3,2024-10-03,East,l,890.0,3.0,37.0,Cash
3,3,4,2024-10-04,West,Books,725.0,1.0,45.0,Debit Card
4,4,5,2024-10-05,North,Electronics,1500.0,1.0,29.0,Credit Card
5,5,6,2024-10-06,North,Home,670.0,4.0,37.0,UPI
6,6,7,2024-10-07,South,Clothing,725.0,2.0,38.0,Cash
7,8,9,2024-10-09,East,Electronics,2100.0,1.0,27.0,Credit Card
8,9,10,2024-10-10,West,l,780.0,5.0,41.0,UPI
9,10,11,2024-10-11,North,Home,560.0,3.0,33.0,Debit Card
10,11,12,2024-10-12,South,Clothing,725.0,2.0,37.0,Cash
11,12,13,2024-10-13,East,Books,420.0,2.0,48.0,Credit Card
12,14,15,2024-10-15,North,Home,920.0,4.0,35.0,UPI
13,15,16,2024-10-16,North,Clothing,510.0,3.0,42.0,Cash
14,16,17,2024-10-17,East,Books,380.0,2.0,37.0,Debit Card
15,17,18,2024-10-18,West,Electronics,725.0,1.0,31.0,Credit Card
16,18,19,2024-10-19,North,Home,1100.0,1.0,39.0,UPI

Task : 4 Custom Aggregation

1.Create a function sales_range() that returns max - min of sales

In [192]:
def sales_range(x):
    return x.max()-x.min()
sales_range =df['sales_amount'].agg(sales_range)
sales_range

1720.0

2.Apply it to find sales range for each region

In [194]:
def sales_range(x):
    return x.max()-x.min()
range = df.groupby('region')['sales_amount'].agg(sales_range)
range

region
East     1720.0
North     990.0
South     275.0
West       55.0
Name: sales_amount, dtype: float64

3 . use.agg() to calculate multilple metrics by region:


    . sales_amount : sum,mean,max
    . quantity : sum,min

In [197]:
result =df.groupby('region').agg({"sales_amount":["sum","mean","max"],
                                 "quantity":["sum","min"] })
result

       sales_amount                     quantity
                sum        mean     max      sum  min
region
East         3790.0  947.500000  2100.0      8.0  1.0
North        6460.0  922.857143  1500.0     18.0  1.0
South        1900.0  633.333333   725.0      9.0  2.0
West         2230.0  743.333333   780.0      7.0  1.0